name: SimplePortals
version: '1.7.7'
api-version: 1.13
main: xzot1k.plugins.sp.SimplePortals
author: XZot1K
description: A simple yet effective way to create portals for your server!
softdepend: [ Multiverse-Core, MultiWorld, Prisma ]
commands:
  simpleportals:
    default: op
    aliases: [ portals, portal, sportal, sportals, sp ]
    permission: simpleportals.use
permissions:
  simpleportals.admin:
    default: op
    description: Gives the player permission to everything in the plugin.
    children:
      simpleportals.use: true
      simpleportals.showregion: true
      simpleportals.setlocation: true
      simpleportals.setswitchlocation: true
      simpleportals.info: true
      simpleportals.reload: true
      simpleportals.create: true
      simpleportals.delete: true
      simpleportals.list: true
      simpleportals.switchserver: true
      simpleportals.selectionmode: true
      simpleportals.portals.*: true
      simpleportals.addcommand: true
      simpleportals.clearcommands: true
      simpleportals.togglecommandonly: true
      simpleportals.fill: true
      simpleportals.viewcommands: true
      simpleportals.toggle: true
      simpleportals.cooldown: true
      simpleportals.delay: true
      simpleportals.find: true
  simpleportals.showregion:
    default: op
    description: Allows the player to view a portal's region.
  simpleportals.setlocation:
    default: op
    description: Allows the player to set a portal's teleport location.
  simpleportals.setswitchlocation:
    default: op
    description: Allows the player to set a portal's switch server location.
  simpleportals.info:
    default: op
    description: Allows the player to view the plugin's information.
  simpleportals.reload:
    default: op
    description: Allows the player to reload the configuration files.
  simpleportals.create:
    default: op
    description: Allows the player to create a portal.
  simpleportals.delete:
    default: op
    description: Allows the player to delete a portal.
  simpleportals.list:
    default: op
    description: Allows the player to list all portals.
  simpleportals.switchserver:
    default: op
    description: Allows the player to change the server a portal can teleport a player to using BungeeCord.
  simpleportals.selectionmode:
    default: op
    description: Allows the player to enter/exit selection mode.
  simpleportals.portals.*:
    default: op
    description: Allows the player to use all portals.
  simpleportals.addcommand:
    default: op
    description: Allows the player to add a command to a portal.
  simpleportals.clearcommands:
    default: op
    description: Allows the player to clear all commands from a portal.
  simpleportals.togglecommandonly:
    default: op
    description: Allows the player to toggle command only mode for a portal.
  simpleportals.fill:
    default: op
    description: Allows the player to fill a portal region with specific materials.
  simpleportals.viewcommands:
    default: op
    description: Allows the player to view the commands of a portal.
  simpleportals.toggle:
    default: op
    description: Allows the player to toggle a portal entirely.
  simpleportals.message:
    default: op
    description: Allows the sender to use the message setting command for portals.
  simpleportals.dm:
    default: op
    description: Allows the sender to use the disable messages command for portals.
  simpleportals.use:
    default: op
    description: Allows the sender to use the basic /simpleportals command.
  simpleportals.cooldown:
    default: op
    description: Allows the sender to use the /simpleportals cooldown command.
  simpleportals.delay:
    default: op
    description: Allows the sender to use the /simpleportals delay command.
  simpleportals.find:
    default: op
    description: Allows the sender to use the /simpleportals find command.